var quotesJokes = [
  'How do you comfort a JavaScript bug? a. You console it',
  'When a JavaScript date has gone bad, “Don’t call me, I’ll callback you. I promise!"',
  'Dev1 saw a strange JavaScript function & asked, “What is this?”. Dev2 responded, “I don’t know. I would’ve called you, but I was in a bind”',
  'Two JavaScript developers walked into the variable bar. Ouch!',
  'Why was the JavaScript developer sad? a. Because he didn’t Node how to Express himself',
  'Why did Jason cover himself with bubble wrap? a. Because he wanted to make a cross-domain JSONP request',
  'Why did the software company hire drama majors from Starbucks? a. Because they needed JavaScript experts!',
  'Why did the CoffeeScript developer keep getting lost? a. Because he couldn’t find his source without a map',
  'What do you call __proto__? a. Dunder proto q. Michael Scott was the regional manager where? a. __mifflin__',
  'How did the doctor revive the developer? a. The dev wasn’t responsive so the doc picked him up by his bootstraps',
  'Why did the developer go broke? a. Because he used up all his cache',
  'Why did the C# developer fall asleep? a. Because he didn’t like Java.',
  'Why did the JavaScript boxer goto the chiropractor? a. Because his backbone was angular from a knockout and required attention',
  'How did the web developer hurt Comic Sans feelings? a. Once he saw the font he quickly changed it to Open Sans and exclaimed “In your @font-face!”',
  'Why do C# and Java developers keep breaking their keyboards a. Because they use a strongly typed language',
  'Why was Ember.js turning red? a. Because it was EMBERrassed for not remEMBERing its route home',
  'Why did the jQuery developer never have financial problems? a. Because he was in $.noConflict() mode',
  'How many programmers does it take to change a light bulb? - None, its hardware problem.',
  'Project Manager is a Person who thinks nine women can deliver a baby in One month.',
  'A user interface is like a joke. If you have to explain it, it’s not that good.',
  'Ubuntu is an ancient African word, meaning "I can\'t configure Debian"',
  'A SQL query goes into a bar, walks up to two tables and asks, "Can I join you?"',
  'How many software testers does it take to change a light bulb? - None. Software testers just noticed that the room was dark. Testers don\'t fix the problems, they just find them.',
  'An SEO expert walks into a bar, bars, beer garden, hangout, lounge, night club, mini bar, bar stool, tavern, pub, beer.',
  'A beginning programmer walks into a bar, takes a look around and says "Hello World!”',
  '“Knock, knock.” - “Who’s there?” very long pause…. - “Java.”',
  'A programmer’s wife send him to the grocery store with the instructions "Get a loaf of bread, and if they have eggs, get a dozen.”. He comes home with a dozen loaves of bread and tells her: „They had eggs.”.',
  'Chuck Norris always uses his own design patterns, and his favorite is the Round­house Kick.',
  'An optimist will tell you the glass is half-full; the pessimist, half-empty; and the engineer will tell you the glass is twice the size it needs to be.',
  'The problem with GIT jokes is that everyone has their own version.',
  'Why programmers like UNIX? unzip, strip, touch, finger, grep, mount, fsck, more, yes, fsck, fsck, fsck, umount, sleep',
  '; - Hide and seek champion.',
  'A Pig and a Chicken are walking down the road. The Chicken says: "Hey Pig, I was thinking we should open a restaurant!" Pig replies: "Hm, maybe, what would we call it?" The Chicken responds: "How about \'ham-n-eggs\'?" The Pig thinks for a moment and says: "No thanks. I\'d be committed, but you\'d only be involved."',
  'A blonde, a drunk and an alien walk up to a bar, but it’s a Microsoft bar, so it’s closed.',
  'People can be divided into two groups: those who do backups, and those who will.',
  'There are only 10 types of people in the world: those who understand binary and those who don\'t.',
  'A guy walks into a bar and asks for 1.4 root beers. The bartender says "I\'ll have to charge you extra, that\'s a root beer float". The guy says "In that case, better make it a double."',
  'There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors',
  'Whats the object-oriented way to become wealthy? Inheritance',
  'To understand recursion, you first must understand recursion'
]


module.exports = quotesJokes;
